server:
  port: 8080
  servlet:
    session:
      timeout: 21600
  #tomcat.max-threads: 6
  tomcat.uri-encoding: UTF-8
spring:
  application:
    name: pp-manage #在注册中心显示的名字
  datasource:
    url: jdbc:mysql://192.168.150.128:3306/pp_manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: liveHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1 #連接測試
  redis:
    # 连接超时时间（毫秒）
    timeout: 8000
    database: 0
    lettuce:
      pool:
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
      timeout: 8000
    cluster:
      max-redirects: 3
      nodes: 192.168.150.128:6380,192.168.150.128:6381,192.168.150.128:6382,192.168.150.128:6383,192.168.150.128:6384,192.168.150.128:6385
      timeout: 1000
    main:
      allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.hzp.test.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

jwt:
  token-header: Authorization
  expire: -1
  secret: xx1WET12^%3^(WE45


