server:
  port: 8080
  servlet:
    session:
      timeout: 21600
  #tomcat.max-threads: 6
  tomcat.uri-encoding: UTF-8
spring:
  application:
    name: pp-manage #在注册中心显示的名字
  datasource:
    url: jdbc:mysql://localhost:3306/pp_manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong&autoReconnect=true&allowMultiQueries=true
    username: pp
    password: MbQE60PxDUTjtKMn
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #连接池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: liveHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1 #連接測試
mybatis:
  type-aliases-package: com.hzp.test.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#MyBatis使用pageHelper分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true



